name = "steamcommunitx"
main = "worker.js"
compatibility_date = "2026-05-09"

routes = [
  { pattern = "steamcommunitx.com/*", zone_name = "steamcommunitx.com" }
]

[vars]
GA_ID = "G-5ZTR404EG7"
MATOMO_URL = "//m.unt1.com/"
MATOMO_SITE_ID = "3"

[[kv_namespaces]]
binding = "STEAM_ID_CACHE"
id = "3ddd6b06496d482a9cd55a9d6079e753"

[observability.logs]
enabled = true
invocation_logs = false
